#!/usr/bin/env bash

dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
	echo "no xdg config home"
	echo "using ~/.config"
	XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
	echo "env var DEV_ENV needs to be present"
	exit 1
fi

if [[ $1 == "--dry" ]]; then
	echo "[[ DRY RUN ]]"
	dry_run="1"
fi

log() {
	if [[ $dry_run == "1" ]]; then
		echo "[DRY_RUN]: $1"
	else
		echo "$1"
	fi
}

log "env: $DEV_ENV"

update_files() {
	log "copying over files from: $1"
	# change to given directory
	pushd $1 &> /dev/null
	(
		# find directories in the $1 path
		configs=`find . -mindepth 1 -maxdepth 1 -type d`
		for c in $configs; do
			# Bash Wizardry for found path
			directory=${2%/}/${c#./}

			# Remove old Directory
			log "   removing: rm -rf $directory"
			if [[ $dry_run == "0" ]]; then
				rm -rf $directory
			fi

			# Copy new one over to old place
			log "   copying env: cp $c $2"
			if [[ $dry_run == "0" ]]; then
				cp -r ./$c $2
			fi
		done
	)
	# return to previous directory
	popd &> /dev/null
}

copy() {
	# Remove Old
	log "removing: $2"
	if [[ $dry_run == "0" ]]; then
		rm $2
	fi

	# Copy New to old location
	log "copying: $1 to $2"
	if [[ $dry_run == "0" ]]; then
		cp $1 $2
	fi
}

# Update config directory
update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
# Update .local directory
update_files $DEV_ENV/env/.local $HOME/.local

# Copy Individual Files
copy $DEV_ENV/env/.zshrc $HOME/.zshrc
copy $DEV_ENV/dev-env $HOME/.local/scripts/dev-env # this script
