#!/usr/bin/env bash

# Find selected directory
selected=$(find ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename $selected | tr ":,. " "____") # tr char replacement

echo $selected $selected_name

# if there is a session navigate to it,
# else create session, then navigate to it
switch_to() {
    if [[ -z "$TMUX" ]]; then
        tmux attach-session -t $selected_name
    else
        tmux switch-client -t $selected_name
    fi
}

if tmux has-session -t $selected_name 2> /dev/null; then
    switch_to 
    exit 0
fi

# We don't have a session so we make one
tmux new-session -ds $selected_name -c $selected
# and switch to it
switch_to
# and run our ready_tmux script
tmux send-keys -t $selected_name "ready_tmux" 

