#!/usr/bin/env bash
log "////////////////"
log "//// langs"
log "///////////"

# 1 is DRY 0 is WET
dry_run=${dry_run:-"1"}

# Rust
log "Installing Rustup"
if [[ $dry_run == "0" ]]; then
    if ! hash rustup; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    else
        log "Rust already Installed"
    fi
else
    if ! hash rustup; then
        log "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh "
    else
        log "Rust already Installed"
    fi
fi

# Node Version Manager
log "Installing Node Version Manager"
if [[ $dry_run == "0" ]]; then
    if ! hash nvm 2>/dev/null; then
        release=$(curl -L https://api.github.com/repos/nvm-sh/nvm/releases/latest 2>/dev/null | jq .name | tr -d '"')
        nvm_release_url=https://raw.githubusercontent.com/nvm-sh/nvm/$release/install.sh
        log "  Latest nvm: $release"
        log "  Using URL: $nvm_release_url"
        curl -o- $nvm_release_url | bash
    else
        log "NVM already installed"
    fi
else
    if ! hash nvm 2>/dev/null; then
        release=$(curl -L https://api.github.com/repos/nvm-sh/nvm/releases/latest 2>/dev/null | jq .name | tr -d '"')
        nvm_release_url=https://raw.githubusercontent.com/nvm-sh/nvm/$release/install.sh
        log "Latest nvm: $release"
        log "Using URL: $nvm_release_url"
        log "  curl -o- $nvm_release_url | bash"
    else
        log "NVM already installed"
    fi
fi
