#!/usr/bin/env bash

# Install NVIM Latest from github releases nvim-linux64.tar.gz
version="v0.10.4"
if [ ! -z "$NVIM_VERSION" ]; then
	version="$NVIM_VERSION"
fi

echo "Installing NeoVim version: \"$version\""

if [ ! -d $HOME/personal/neovim ]; then
	git clone https://github.com/neovim/neovim.git $HOME/personal/neovim
fi

sudo apt -y install cmake gettext luda5.1 liblua5.1.0-dev

git -C ~/neovim fetch --all
git -C ~/neovim checkout $version

make -C ~/neovim clean
make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make -C ~/neovim install
echo "Done installing NeoVim"

