#!/usr/bin/env bash
#
# 1 is DRY 0 is WET
dry_run=${dry_run:-"1"}

# Install NVIM Latest from github releases nvim-linux64.tar.gz
version="v0.10.4"
if [ ! -z "$NVIM_VERSION" ]; then
    version="$NVIM_VERSION"
fi

log "////////////////"
log "//// nvim"
log "///////////"
log "// Installing NeoVim $version"
log ""

if hash nvim; then
    log "NeoVim already installed"
    exit 0 
fi
if [[ $dry_run == "0" ]]; then
    if [ ! -d $HOME/personal/neovim ]; then
        git clone https://github.com/neovim/neovim.git $HOME/personal/neovim
        sudo apt -y install cmake gettext luda5.1 liblua5.1.0-dev
        git -C ~/neovim fetch --all
        git -C ~/neovim checkout $version

        make -C ~/neovim clean
        make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
        sudo make -C ~/neovim install
    fi
else
    if [ -d $HOME/personal/neovim ]; then
        log "  git clone https://github.com/neovim/neovim.git $HOME/personal/neovim"
        log "sudo apt -y install cmake gettext luda5.1 liblua5.1.0-dev"
        log "git -C ~/neovim fetch --all"
        log "git -C ~/neovim checkout $version"
        log "make -C ~/neovim clean"
        log "make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo"
        log "sudo make -C ~/neovim install"
fi

log "Done installing NeoVim"


