#!/usr/bin/env bash

# TODO: Add checks to ignore if already installed
# 1 is DRY 0 is WET
dry_run=${dry_run:-"1"}

log "////////////////"
log "//// zsh"
log "///////////"

if [[ $dry_run == "0" ]]; then
    # Install zsh
    log "Installing zsh"
    sudo apt install zsh

    # Set as default shell
    log "Setting as default shell"
    sudo chsh -s $(which zsh)

    # Install Oh-My-Zsh
    log "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

else
    log "Installing zsh"
    log "  sudo apt install zsh"
    log "Setting as default shell"
    log "  sudo chsh -s $(which zsh)"
    log "Installing oh-my-zsh"
    log '  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
fi


