#!/usr/bin/env bash

# TODO: Add checks to ignore if already installed
# 1 is DRY 0 is WET
dry_run=${dry_run:-"1"}

log "////////////////"
log "//// zsh"
log "///////////"

if [[ $dry_run == "0" ]]; then
    # Install zsh
    log "Installing zsh"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install zsh
    else
        sudo apt install zsh
    fi

    # Set as default shell
    log "Setting as default shell"
    sudo chsh -s $(which zsh)

    # Install Oh-My-Zsh
    log "Installing oh-my-zsh"
    ZSH=$ZSH sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

else
    log "Installing zsh"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        log "  brew install zsh"
    else
        log "  sudo apt install zsh"
    fi
    log "Setting as default shell"
    log "  sudo chsh -s $(which zsh)"
    log "Installing oh-my-zsh"
    log '  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
fi


