#!/usr/bin/env bash

# If there's an executable in the current dir, run it
if [[ -x ".ready_tmux" ]]; then
    ./.ready_tmux
# Else run the one in the home directory
elif [[ -x "~/.ready_tmux" ]]; then
    ~/.ready_tmux
fi
clear
